# resultado = 10 / 0 

try:
    #codigo que pede pode causar um erro 
    resultado = 10 / 0
except:
    # codigo que trata o erro 
    print("Ocorreu um erro durante a operação!")